@startuml kata
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(org, "Organiser")
Person(speaker, "Speaker")
Person(attendee, "Attendee")

System(idam, "AWS Cognito")
System_Ext(cfp, "Sessonize.com")

System(cms, "Conference Site Generator")
Container(conf, "Conf CMS", "React on AWS Amplify Console", "Responsive Web App for Conference")
Rel_D(cms, conf, "Publishes", "AWS API")
Rel_L(conf, cfp, "Get schedule", "JSON/HTTP")

Container(feedback, "UGC", "AWS Lambda", "Back-end for UGC")
ContainerDb(feedbackDb, "UGC", "AWS S3")

Rel(conf, idam, "Authenticates", "Oauth")
Rel(conf, idam, "Update attendee details", "Cognito API")
Rel_D(conf, feedback, "Persists feedback", "JSON/HTTPS")
Rel_D(feedback, feedbackDb, "Persists feedback", "S3 API")

Container(notify, "Notifier", "AWS CloudWatch & Lambda", "Notifies customers of schedule change")
ContainerDb(schedule, "Schedule", "AWS S3")
Rel(notify, schedule, "Persists current schedule", "S3 API")


Rel(org, cfp, "Manage CFP and Schedule", "HTTPS")
Rel(notify, cfp, "Get schedule", "JSON/HTTP")
Rel(cms, idam, "Create customer directory", "Cognito API")

Rel(notify, attendee, "SMS notifications", "AWS SNS API")
Rel(notify, idam, "Cognito ListUsers", "Cognito API")

Rel(org, cms, "Creates sites", "HTTPS")
Rel(org, conf, "Creates content", "HTTPS")
Rel(org, conf, "Publish speaker slides", "HTTPS")
Rel(speaker, cfp, "Register/Login", "HTTPS")
Rel(speaker, cfp, "Submits talk", "HTTPS")

Rel(attendee, conf, "Register/Login", "HTTPS")
Rel(attendee, conf, "Update notification status", "HTTPS")
Rel(attendee, conf, "View content", "HTTPS")
Rel(attendee, conf, "Vote on talk", "HTTPS")
Rel(org, conf, "Adds feedback", "HTTPS")
Rel(speaker, conf, "View feedback", "HTTPS")

@enduml
